software: "pim-community-dev"
version: "master"
data:
  -
    comment: 'An integration or end-to-end test'
    folders:
      - "tests/back/Integration/"
      - "tests/back/Channel/EndToEnd/"
      - "tests/back/Channel/Integration/"
      - "tests/back/Pim/Enrichment/EndToEnd"
    commands:
      - "APP_ENV=dev make up"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c phpunit.xml.dist {{FILEPATH}}"

  -
    comment: "A unit test with PHPSpec"
    folders:
      - "tests/back/Acceptance/spec/"
      - "tests/back/Channel/Specification/"
      - "src/Akeneo/Channel/back/tests/Specification/"
      - "src/Akeneo/Tool/Component/Batch/spec/"
    commands:
      - "APP_ENV=test docker-compose run -u www-data --rm php php vendor/bin/phpspec run {{FILEPATH}}"

  -
    comment: "An integration test related to Connectivity"
    folders:
      - "src/Akeneo/Connectivity/Connection/back/tests/Integration/"
    commands:
      - "APP_ENV=dev make up"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c . --testsuite Akeneo_Connectivity_Connection_Integration {{FILEPATH}}"

  -
    comment: "An integration test related to Channel"
    folders:
      - "src/Akeneo/Channel/back/tests/Integration/"
    commands:
      - "APP_ENV=dev make up"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c src/Akeneo/Channel/back/tests --testsuite Channel_Integration_Test {{FILEPATH}}"
