software: pim-enterprise-dev
version: master
data:
  -
    comment: "A unit test with PHPSpec"
    folders:
      - "components/tailored-export/back/tests/Specification"
      - "components/tailored-import/back/tests/Specification"
      - "src/Akeneo/AssetManager/tests/back/spec"
      - "src/Akeneo/ReferenceEntity/tests/back/spec"
    commands:
      - "APP_ENV=test docker-compose run -u www-data --rm php php vendor/bin/phpspec run {{FILEPATH}}"

  -
    comment: "An integration test related to Assets"
    folders:
      - "src/Akeneo/AssetManager/tests/back/Integration/"
    commands:
      - "make pim-test"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c src/Akeneo/AssetManager/tests/back --testsuite AssetFamily_Integration_Test {{FILEPATH}}"

  -
    comment: "An integration test related to Reference Entities"
    folders:
      - "src/Akeneo/ReferenceEntity/tests/back/Integration/"
    commands:
      - "make pim-test"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c src/Akeneo/ReferenceEntity/tests/back --testsuite ReferenceEntity_Integration_Test {{FILEPATH}}"

  -
    comment: "An integration test related to Tailored Import"
    folders:
      - "components/tailored-import/back/tests/Integration"
    commands:
      - "make pim-test"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c components/tailored-import/back/tests/phpunit-ee.xml --testsuite TailoredImport_Integration_Test {{FILEPATH}}"

  -
    comment: "An integration test related to Tailored Export"
    folders:
      - "components/tailored-export/back/tests/Integration"
    commands:
      - "make pim-test"
      - "APP_ENV=test docker-compose run -u www-data -T php vendor/bin/phpunit -c . --testsuite TailoredExport_Integration_Test {{FILEPATH}}"
