software: "pim-enterprise-dev"
version: "master"
data:
  -
    comment: "A unit test with PHPSpec"
    folders:
      - "components/tailored-export/back/tests/Specification"
      - "components/tailored-import/back/tests/Specification"
    commands:
      - "APP_ENV=test docker-compose run -u www-data --rm php php vendor/bin/phpspec run {{FILEPATH}}"

  -
    comment: "A unit test with PHPSpec related to Assets"
    folders:
      - "src/Akeneo/AssetManager/tests/back/spec"
    commands:
      - "O={{FILEPATH}} PIM_CONTEXT=asset-manager APP_ENV=test make asset-manager-unit-back"

  -
    comment: "A unit test with PHPSpec related to Reference Entity"
    folders:
      - "src/Akeneo/ReferenceEntity/tests/back/spec"
    commands:
      - "O={{FILEPATH}} PIM_CONTEXT=reference-entity make reference-entity-unit-back"

  -
    comment: "An integration test related to Assets"
    folders:
      - "src/Akeneo/AssetManager/tests/back/Integration/"
    commands:
      - "make pim-test"
      - "O={{FILEPATH}} PIM_CONTEXT=asset-manager APP_ENV=test make asset-manager-integration-back"

  -
    comment: "An integration test related to Reference Entities"
    folders:
      - "src/Akeneo/ReferenceEntity/tests/back/Integration/"
      - "tests/back/Pim/Enrichment/ReferenceEntity/Integration/"
    commands:
      - "make pim-test"
      - "O={{FILEPATH}} PIM_CONTEXT=reference-entity APP_ENV=test make reference-entity-integration-back"

  -
    comment: "An integration test related to Tailored Import"
    folders:
      - "components/tailored-import/back/tests/Integration"
    commands:
      - "make pim-test"
      - "O={{FILEPATH}} PIM_CONTEXT=tailored-import make integration-back"

  -
    comment: "An acceptance test related to Tailored Import"
    folders:
      - "components/tailored-import/back/tests/Acceptance/"
    commands:
      - "O={{FILEPATH}} PIM_CONTEXT=tailored-import make acceptance-back"

  -
    comment: "An integration test related to Tailored Export"
    folders:
      - "components/tailored-export/back/tests/Integration"
    commands:
      - "make pim-test"
      - "O={{FILEPATH}} PIM_CONTEXT=tailored-export make integration-back"

  -
    comment: "An acceptance test related to Tailored Export"
    folders:
      - "components/tailored-export/back/tests/Acceptance/"
    commands:
      - "O={{FILEPATH}} PIM_CONTEXT=tailored-export make acceptance-back"

  -
    comment: "An integration test related to Enrichment"
    folders:
      - "tests/back/Pim/Enrichment/Integration/"
      - "tests/back/Pim/Enrichment/ReferenceEntity/EndToEnd/"
    commands:
      - "O={{FILEPATH}} PIM_CONTEXT=enrichment-product APP_ENV=test make enrichment-product-integration-back"
